### ISSUE TITLE
Remove Glow and blue border

### ISSUE THREAD

**Issue by alaksandarjesus** [sebastianha/angular-bootstrap-checkbox#10]
When i click on the checkbox i am getting a glow or border around it. How to remove it.

Thanks for providing such a wonderful directive.

**Comment by alaksandarjesus** [comment]
The blur is not working now. Thanks. I will look into my code what was the difference with it.

**Comment by alaksandarjesus** [comment]
This code removed it.

.btn:focus,.btn:active:focus,.btn.active:focus,
.btn.focus,.btn:active.focus,.btn.active.focus {
    outline: none;
}

Thanks to 

http://stackoverflow.com/questions/21201080/bootstrap-button-remove-outline-on-chrome-os-x

**Comment by sebastianha** [comment]
Thanks for the info, I will include this in the next release!
