### ISSUE TITLE
Conditional classes with ng-class

### ISSUE THREAD

**Issue by Tomino2112** [sebastianha/angular-bootstrap-checkbox#24]
Hi,

I realize that this might be issue with ngClass itself, but maybe you will find solution. 

when I write: `<checkbox ng-class={'btn-success':isActive}>`

it gives me an error. Inspecting code, the result is something like: 
`... ng-class:{'btn-success':isActive} {'btn-xs':size==='default'} ...`

Apparently merging of ng-class is not being done properly.

Any way to fix this, or work around it?

**Comment by sebastianha** [comment]
See https://github.com/sebastianha/angular-bootstrap-checkbox/tree/ng-class branch for a general solution. I will be merged as soon as is tested.
