### ISSUE TITLE
checkbox default check.

### ISSUE THREAD

**Issue by umair-khanzada** [sebastianha/angular-bootstrap-checkbox#28]
how checkbox default check 
i tried checked attribute and also try ng-checked attribute but not work.

**Comment by sebastianha** [comment]
Just set the model value to the default value you want. This should work.

**Comment by umair-khanzada** [comment]
but not have an attribute and also ng-checked="true" is not working for this.
i work same like your trick.

**Comment by ihamouda** [comment]
Same issue, my ng-model value  = 1, the check box is unchecked and the model value changes to 0

here is my checkbox
`<checkbox
                ng-model="db.selectedGroup.is_primary"
                ng-true-value="1"
                ng-false-value="0"
                ></checkbox>`

and here is my object if the checkbox is not in the page
`group_description: "",
group_id: "db1-cfb5df1c-6027-11e4-b1b7-525400b87f6d",
group_name: "Execs",
is_primary: 1`

then here is my object again when the checkbox is in the page

`group_description: "",
group_id: "db1-cfb5df1c-6027-11e4-b1b7-525400b87f6d",
group_name: "Execs",
is_primary: "0"`

any suggestions?

**Comment by sebastianha** [comment]
At a first look you are mixing strings and integers, could this be the problem?

is_primary is 1 (int) at first and then "0" (string)

**Comment by sebastianha** [comment]
Please reopen if the problem still exists
