### ISSUE TITLE
Indeterminate / Tri-State / Three-State

### ISSUE THREAD

**Issue by sroe** [sebastianha/angular-bootstrap-checkbox#3]
Hi,
your Checkbox lacks support of the indeterminate state as it is part of the future standard html5 see http://www.w3.org/html/wg/drafts/html/master/forms.html#checkbox-state-(type=checkbox)
Just as a hint :wink: 
And thank you for sharing your work!
Regards

**Comment by achadee** [comment]
+1 to this! keep up the good work:)

**Comment by sebastianha** [comment]
Finally I implemented this, see release 0.5.0
Let me now if this works for you!

**Comment by michahell** [comment]
Hmm, we are having trouble getting the indeterminate state to work, could you maybe include a small example on the readme ? for some reason, we cannot change the checkbox model value to any value we specify the indeterminate state to be, only **true** or **false** are somehow allowed. How does that work anyway ?

**Comment by sebastianha** [comment]
Did you check the index.html? There is an example for the tri-stage box. When you set it to "undefined" it should work.
