### ISSUE TITLE
How do I include this in my app module?

### ISSUE THREAD

**Issue by aodendaal** [sebastianha/angular-bootstrap-checkbox#36]
I've installed the package via **npm** and confirmed it's in my _node_modules_ directory but I cannot figure out how to include it in my app module.

This is what I tried, but it doesn't work

    import { ui } from 'angular-bootstrap-checkbox';
    ...

    @NgModule({
    declarations: [
      ...
    ],
    imports: [
      ...
      ["ui.checkbox"]
    ],
    providers: [
      ...
    ]
    })
    export class AppModule { }

How do I include this package into my project?

**Comment by sebastianha** [comment]
Hi,

which version of angular are you using?

**Comment by carkod** [comment]
Same, I have angular 5

**Update**: I think this only works with AngularJS

**Comment by sebastianha** [comment]
Hi, this module is for angular 1.x only, sorry
