### ISSUE TITLE
Checkbox does not support disable

### ISSUE THREAD

**Issue by daerogami** [sebastianha/angular-bootstrap-checkbox#38]
Unless there is something I am missing, I don't see anyway to use the disable attribute nor the ng-disable directive with this.

**Comment by sebastianha** [comment]
See the Index.html for an example using the ng-disabled attribute,

**Comment by daerogami** [comment]
`ng-disabled` wasn't working for me when I tried it, but that could very well be on my usage. As long as there's docs suggesting it should work, I'm satisfied. Thanks!
